#!/bin/bash
SCRIPT=`basename $0`
OGGINFO=/tmp/$SCRIPT-ogginfo.$$
DELETE=0

usage() {
    echo "Usage: $0 [-d] <dir>" 
    exit 1
}

process_dir() {
    for OGG in `find $1 -name "*.ogg"`
    do
        MP3=${OGG%%.ogg}.mp3  
        convert $OGG $MP3
    done
}

convert() {
    LANG=C ogginfo $1 > $OGGINFO
    echo "Converting... $1"
    BITRATE=`grep "^Nominal bitrate:" $OGGINFO | awk '{print $3}' | cut -f1 -d.`
    RATE=`grep "^Rate:" $OGGINFO | awk '{print $2}'`
    CHANNELS=`grep "^Channels:" $OGGINFO | awk '{print $2}'`
    TITLE=`grep TITLE= $OGGINFO | cut -f2- -d=`
    ARTIST=`grep ARTIST= $OGGINFO | cut -f2- -d=`
    ALBUM=`grep ALBUM= $OGGINFO | cut -f2- -d=`
    DATE=`grep DATE= $OGGINFO | cut -f2- -d=`
    TRACKNUMBER=`grep TRACKNUMBER= $OGGINFO | cut -f2- -d=`
    GENRE=`grep GENRE= $OGGINFO | cut -f2- -d=`
    rm -f $OGGINFO

    oggdec $1 -Q -o - | lame -b $BITRATE -h - $2 > /dev/null
    id3v2 -a "$ARTIST" -A "$ALBUM" -t "$TITLE" -g "$GENRE" -y "$DATE" -T "$TRACKNUMBER" $2
    [ $DELETE -eq 1 ] && rm $1
}

if [ $# -lt 1 ]
then
    usage
fi

if [ "$1" = "-d" ]
then
    echo "Will delete file after convert"
    shift 
    DELETE=1
fi

process_dir $1
